### ISSUE TITLE
Model download error on release

### ISSUE THREAD

**Issue by Lucien-MG** [demixr/demixr-app#28]
![Screenshot_20220114_160602_com demixr demixr_app](https://user-images.githubusercontent.com/45817540/149537681-02561792-6c93-421c-87ca-32d606e56cdf.jpg)

**Comment by Marc-Demoustier** [comment]
Hi @Lucien-MG,

Thank you for this issue.
This problem is fixed on the last release, you can find it [here](https://github.com/demixr/demixr-app/releases/tag/v0.0.6).
