### ISSUE TITLE
App description

### ISSUE THREAD

**Issue by IzzySoft** [demixr/demixr-app#29]
Is there a description available on what this app is intended for and which features it provides? Would be great if there was at least a rough outline, so nobody gets disappointed after download & install that it was something completely "unexpected" :wink: Thanks!

**Comment by guillaume-merle** [comment]
Hello and thanks for the interest, the project is still in early development and the description should be available soon, in the next few days.

**Comment by IzzySoft** [comment]
Thanks a lot! Wishing best progress then. Will take another look when an update (or closure) of this issue suggests.

**Comment by IzzySoft** [comment]
Thanks for the update – much clearer now! Unfortunately, the size of the APKs exploded by factor 8. Was that intended? They were around 8M a week ago, now they're beyond 64M each.

**Comment by guillaume-merle** [comment]
Yes that is normal, a week ago the releases did not contain the core logic of the application: the music source separation (with Pytorch). The release then only contained the workflow and other features of the app, and were mostly there for testing.
But we did not work yet on reducing the size of the APKs, so there is room for improvement there.

**Comment by IzzySoft** [comment]
Thanks for confirming! I mostly asked because in the past I experienced more than one case where the devs were shocked (so it was NOT intended) and finally found out "something slipped in" – which they then removed again. OK, then that's the way it should be…
