### ISSUE TITLE
Add demixing percentage

### ISSUE THREAD

**Issue by Marc-Demoustier** [demixr/demixr-app#35]
Display a progress bar on the processing screen while demixing.

**Comment by guillaume-merle** [comment]
We can use [Event Channels](https://api.flutter.dev/flutter/services/EventChannel-class.html) to be able to send via a Stream the progress of the demixing from Android to Flutter.

Some examples:
* https://medium.com/@igaurab/event-channels-in-flutter-2b4d0db0ee4f
* https://www.raywenderlich.com/20518849-an-in-depth-dive-into-streaming-data-across-platform-channels-on-flutter
